### ISSUE TITLE
求教博主大大

### ISSUE THREAD

**Issue by SomnusWu** [ZBJDSBJ/ScaleRuler#2]
博主大大 小生不才 你能把体重那个控件 倒过来下吗  .

**Comment by ZBJDSBJ** [comment]
修改一下 ：canvas.drawLine(xPosition, getHeight(), xPosition, getHeight() - mDensity \* ITEM_MAX_HEIGHT, mLinePaint);  的float startY 和float stopY就可以了

**Comment by SomnusWu** [comment]
好像还是不会改哦  . V_V

**Comment by ZBJDSBJ** [comment]
推荐一个博客给你学习 http://www.gcssloop.com 授你渔
